### ISSUE TITLE
Comment array not formatted correctly

### ISSUE THREAD

**Issue by lbogaardt** [eEcoLiDAR/laserchicken#123]
Currently, the comment section of the output ply contains an array which is formatted like:

> comment [
comment {'version': '1.0', 'time': '2018-08-19 16:34:51.491283'}
,comment {'version': '2.0', 'time': '2018-08-20 16:34:51.491562'}
,comment {'version': '3.0', 'time': '2018-08-21 16:34:51.491562'}
comment ]

I believe this does not conform to the PLY format, which states 

> Comments may be placed in the header by using the word comment at the start of the line.

The comma between each array element should be at the end of the line, not the begining.

**Comment by cwmeijer** [comment]
This functionality was tested only on a single comment (which it passes of course). Test (and code) should be extended for multiple lines like in the example above.
