### ISSUE TITLE
Create digital terrain model (DTM) module

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/laserchicken#34]
The module should input a pointcloud with attribute whether each point is a ground point or not and should output a TIFF.

Calculate the distance from the vegetation point related to the ground point. Ground points can be rasterized within the cylinder or calculate the mean of all ground points within the cylinder and then calculate the difference between each vegetation point.

All feature extractors need to implement the feature extractor interface from #19.

**Comment by komazsofi** [comment]
LAStools lasheight function able to this calculation as following (from LAStools README):

"This tool computes the height of each LAS point above the
  ground. This assumes that grounds points have already been
  classified (classification == 2) so they can be identified
  and used to construct a ground TIN. The ground points can
  also be in an separate file '-ground_points ground.las' or
  '-ground_points dtm.csv -parse ssxyz'.

  The tool reads LIDAR in LAS/LAZ/ASCII format, triangulates
  the ground points into a TIN (or whatever point class(es)
  were selected with '-class 8' or '-classification 2 8'), and
  calculates the elevation of each point with respect to this
  TIN. "

**Comment by komazsofi** [comment]
https://github.com/eEcoLiDAR/ecolidar_knowledgebase/blob/master/Figures/normheight.PNG?raw=true

**Comment by komazsofi** [comment]
http://geo.tuwien.ac.at/opals/html/ModuleGrid.html

**Comment by komazsofi** [comment]
http://pro.arcgis.com/en/pro-app/help/analysis/geostatistical-analyst/how-local-polynomial-interpolation-works.htm summary about different interpolation techniques

**Comment by cwmeijer** [comment]
Here's some code that I wrote that can be used for this item. Some other features extractors will also need to fit planes so this code should be in some central spot. For interpolation for the ground, we should probably use planefitting like in this code. Other options are IDW or nearest neighbor etc but plane fitting seems to make sense and is not very slow to do. The function below should be expanded to be able to cope with some strange situations like too few points etc.


import numpy as np


def fit_plane(x, y, a):
    """
    Fits a plane through the data and returns a function that returns the height of the plane given an x and y.

    :param x: x coordinates
    :param y: y coordinates
    :param a: value (for instance height)
    :return:
    """
    matrix = np.column_stack((np.ones(x.size), x, y))
    parameters, _, _, _ = np.linalg.lstsq(matrix, a)

**Comment by komazsofi** [comment]
In the AHN2 data (which was classified by LAStools beforehand): the classification information is saved as classification==1 is the vegetation and classification==2 are the ground.

**Comment by cwmeijer** [comment]
i don't think we are still planning to do this.
