### ISSUE TITLE
Extract feature lacks documentation and error messages

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/laserchicken#70]
I have a problem with running the feature extraction. I do not understand that from HeightStatisticsFeatureExtractor.extract function what  targetpc, targetindex means. Furthermore, somehow the code gives the following error message which indicate that the program somehow can not process this line: z = sourcepc[point]['z']['data'][neighborhood]. 

Traceback (most recent call last):
  File "C:/zsofia/Amsterdam/GitHub/komazsofi/myPhD_escience_analysis/test_laserchicken/mydummytest_laserchicken.py", line 19, in <module>
    (max_z, min_z, mean_z, median_z, std_z, var_z, range_z, coeff_var_z, skew_z, kurto_z) = extractor.extract(pc_out, indices,None,None)
  File "C:/zsofia/Amsterdam/GitHub/eEcoLiDAR/eEcoLiDAR\laserchicken\feature_extractor\height_statistics_feature_extractor.py", line 18, in extract
    z = sourcepc[point]['z']['data'][neighborhood]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

``` python
from laserchicken import read_las
from laserchicken.keys import point
from laserchicken.spatial_selections import points_in_polygon_wkt
from laserchicken import write_ply
from laserchicken import compute_neighbors
from laserchicken.feature_extractor.height_statistics_feature_extractor import HeightStatisticsFeatureExtractor

pc = read_las.read("C:/zsofia/Amsterdam/GitHub/eEcoLiDAR/eEcoLiDAR/testdata/AHN2.las")
pc_out = points_in_polygon_wkt(pc, "POLYGON(( 243590.0 572110.0, 243640.0 572160.0, 243700.0 572110.0, 243640.0 572060.0, 243590.0 572110.0 ))")

indices=compute_neighbors.compute_cylinder_neighbourhood_indicies(pc_out, pc_out, 2.5)
#print(len(indices))
#print(pc_out[point]['z']['data'][indices])

extractor = HeightStatisticsFeatureExtractor()
(max_z, min_z, mean_z, median_z, std_z, var_z, range_z, coeff_var_z, skew_z, kurto_z) = extractor.extract(pc_out, indices,None,None)

write_ply.write(pc_out, "C:/zsofia/Amsterdam/GitHub/komazsofi/myPhD_escience_analysis/test_data/withinplygonply_hightfea.ply")
```

**Comment by komazsofi** [comment]
Some kind of solution from my side:

'''
from laserchicken import read_las
from laserchicken.keys import point
from laserchicken.spatial_selections import points_in_polygon_wkt
from laserchicken import write_ply
from laserchicken import compute_neighbors
from laserchicken.feature_extractor.height_statistics_feature_extractor import HeightStatisticsFeatureExtractor

pc = read_las.read("C:/zsofia/Amsterdam/GitHub/eEcoLiDAR/eEcoLiDAR/testdata/AHN2.las")
pc_out = points_in_polygon_wkt(pc, "POLYGON(( 243590.0 572110.0, 243640.0 572160.0, 243700.0 572110.0, 243640.0 572060.0, 243590.0 572110.0 ))")

indices=compute_neighbors.compute_cylinder_neighbourhood_indicies(pc_out, pc_out, 2.5)
#print(np.array(indices).shape)
#print(pc_out[point]['z']['data'][indices])
#write_ply.write(pc_out, "C:/zsofia/Amsterdam/GitHub/komazsofi/myPhD_escience_analysis/test_data/withinplygonply_hightfea.ply")

output_text = ""

for i in range(len(indices)):
    extractor = HeightStatisticsFeatureExtractor()
    max_z, min_z, mean_z, median_z, std_z, var_z, range_z, coeff_var_z, skew_z, kurto_z = extractor.extract(pc_out,indices[i],None,None)

    output_text += "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s \n" % (pc_out[point]['x']['data'][i],pc_out[point]['y']['data'][i],pc_out[point]['z']['data'][i],max_z, min_z, mean_z, median_z, std_z, var_z, range_z, coeff_var_z, skew_z, kurto_z)

fileout = open('C:/zsofia/Amsterdam/GitHub/komazsofi/myPhD_escience_analysis/test_data/pc_withfea.txt', "w")
fileout.write(output_text)
fileout.close()
'''

**Comment by cwmeijer** [comment]
This is the planned behavior. You are calling the function the way it was supposed to in your loop.
The sort of counterintuitive way of having to use a loop here should be done automatically when the command line tool for this job is in place. Also, the function should raise a more informative error and needs some documentation.

**Comment by cwmeijer** [comment]
I already added some documentation when fixing another bug and cleaning the code. I didn't add an exception yet.

**Comment by cwmeijer** [comment]
documentation and examples have been added
