### ISSUE TITLE
Vectorize features

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/laserchicken#75]
Some features could benefit by vectorizing the calculation. For instance, the eigen value calculation could be quicker by solving for many targets at the same time. For this, instead of the 2d cov matrix, the 3d cov matrix should be be passed to np.linalg.eig. Every slice of the 3d matrix is a simple 2d cov matrix like before. Berend spend some time implementing this. He uses some function called numpy.einsum to calculate this. See the code in link below. interesting parts start at line 109 etc.

[par_pipeline_wijers_edit.txt](https://github.com/eEcoLiDAR/eEcoLiDAR/files/1703239/par_pipeline_wijers_edit.txt)

**Comment by NicoRenaud** [comment]
I've started implemented all that and it does indeed make quite a difference. Do we want to keep the serial and the vectorized extractor ?

**Comment by NicoRenaud** [comment]
Is there a particular reason why the largest eigevalue should be the first returned ?

**Comment by cwmeijer** [comment]
many computationally expensive ones have been vectorized
