### ISSUE TITLE
Feature calculation with the new system is slower

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/laserchicken#87]
I started to test the fixed version of the new compute_features function. It seems to be that this system is slower compared to the previous version (I cannot entriley reconstruct the difference because I pulled the new versions of the software). 

On my test data:

build kd-tree: 4.543108 sec
New laserchicken version calculation of max z took: 9.890318 sec
Simple calculation of max z took: 1.100296 sec

``` python
from laserchicken import read_las
from laserchicken import write_ply
from laserchicken.keys import point
from laserchicken.spatial_selections import points_in_polygon_wkt
from laserchicken.compute_neighbors import compute_neighborhoods
from laserchicken.volume_specification import Sphere, InfiniteCylinder
from laserchicken.feature_extractor import compute_features

import numpy as np
import time

# Import
pc = read_las.read("D:/NAEM/Data/ALS_AHN2/SelStudyArea2_v2.las")
pc_sub = points_in_polygon_wkt(pc, "POLYGON((196550 446510,196550 446540,196580 446540,196580 446510,196550 446510))")

# Neighborhood calculation

start = time.time()
indices_cyl=compute_neighborhoods(pc_sub, pc_sub, InfiniteCylinder(5))
end = time.time()
difftime=end - start
print(("build kd-tree: %f sec") % (difftime))

start1 = time.time()
for i in range(len(indices_cyl)):
    features=compute_features(pc_sub, indices_cyl, pc_sub, ['max_z'], InfiniteCylinder(5))
    #print(features)
end1 = time.time()
difftime1=end1 - start1
print(("New laserchicken version calculation of max z took: %f sec") % (difftime1))

start2 = time.time()
for i in range(len(indices_cyl)):
    max_z=np.max(pc_sub[point]['z']['data'][indices_cyl[i]])
    #print(max_z)
end2 = time.time()
difftime2=end2 - start2
print(("Simple calculation of max z took: %f sec") % (difftime2))
```

**Comment by NicoRenaud** [comment]
I think that when you use

```python
for i in range(len(indices_cyl)):
    features=compute_features(pc_sub, indices_cyl, pc_sub, ['max_z'], InfiniteCylinder(5))
```

**Comment by komazsofi** [comment]
I have already corrected that loop thing. Now I can easily save with one row everything into an pandas data frame;-)

It is possible that user does not want to extract all this feature within this feature group. For example, the situation can be that you find out in a small study area that max, the mean and standard deviation is needed by others, not because highly correlated each other (and represents the nearly the information in the end) than you may when you apply your software to larger area you would not calculate all the features within the height statistic group.  But I do not think about this issue beforehand I tried to structurize the function based on determined feature groups.

**Comment by cwmeijer** [comment]
outdated and I believe it was already fixed
